#!/usr/bin/env python

import os
import sys
import socket
import fcntl
import struct
import logging
import logging.handlers
from cmssysadmin.landb.localpc import LocalPC, get_ip_address

class MailHandler(logging.handlers.SMTPHandler):
	def getSubject(self, record):
		try:
			ip = get_ip_address('em1')
		except IOError:
			ip = get_ip_address('eth0')
		return '[Autoregistration] %s from %s' % (record.levelname, ip)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
smtpHandler = MailHandler(mailhost='localhost', fromaddr='cmsautoregistration@cern.ch', toaddrs='jm.andre@cern.ch', subject='Log from autoregistration script')
smtpHandler.setLevel(logging.INFO)
logger.addHandler(smtpHandler)

try:
	pc = LocalPC()
	pc.register()
	msg = str(pc)
	logger.warning(msg)
except Exception as e:
	logger.exception(e)
	sys.exit(1)
# vim: set ts=2 sw=2 tw=0 noet :
