#!/usr/bin/env python

import os
import time
import sys
import logging
import logging.handlers
from cmssysadmin.landb.localpc import LocalPC, get_ip_address

class MailHandler(logging.handlers.SMTPHandler):
	def getSubject(self, record):
		if record.levelno == logging.CRITICAL:
			return '[Autoregistration] %s is ready to be installed' % record.args[0]
		try:
			ip = get_ip_address('em1')
		except IOError:
			ip = get_ip_address('eth0')
		return '[Autoregistration] %s from %s' % (record.levelname, ip)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
smtpHandler = MailHandler(mailhost='localhost', fromaddr='cmsautoregistration@cern.ch', toaddrs='jm.andre@cern.ch', subject='Log from autoregistration script')
smtpHandler.setLevel(logging.INFO)
logger.addHandler(smtpHandler)

try:
	pc = LocalPC()
	# Registering the PC in LanDB
	pc.register()
	msg = str(pc)
	logger.warning(msg)
	# Registration done
	# Start to wait until we get our new IP
	pc.waitForFinalIP()
	# We got our final IP
	# Time to register in Foreman
	pc.registerForeman()
	logger.critical("Machine %s is now registered in Foreman", pc.shortName)
except Exception as e:
	logger.exception(e)
	sys.exit(1)
# vim: set ts=2 sw=2 tw=0 noet :
